name: Lib.ServerTiming.Abstractions - CD
on:
  push:
    tags:
    - "abstractions-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Extract VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/abstractions-v/}" >> $GITHUB_ENV
      shell: bash
    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Setup .NET 7.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: NuGet Push Lib.ServerTiming.Abstractions
      run: dotnet nuget push src/Lib.ServerTiming.Abstractions/bin/Release/Lib.ServerTiming.Abstractions.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      shell: bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}