name: Continuous Delivery (ASP.NET Core)
on:
  push:
    tags:
    - "aspnetcore-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-test-pack-and-push:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/aspnetcore-v/}" >> $GITHUB_ENV
      shell: bash
    - name: Setup .NET Core 2.1 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '2.1.x'
    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Setup .NET 7.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - name: Restore
      run: dotnet restore src/Lib.AspNetCore.ServerTiming
    - name: Build
      run: dotnet build src/Lib.AspNetCore.ServerTiming --configuration Release --no-restore
    - name: Test
      run: dotnet test test/Test.AspNetCore.ServerTiming --configuration Release
    - name: Pack
      run: dotnet pack src/Lib.AspNetCore.ServerTiming --configuration Release --no-build
    - name: NuGet Push Lib.AspNetCore.ServerTiming
      run: dotnet nuget push src/Lib.AspNetCore.ServerTiming/bin/Release/Lib.AspNetCore.ServerTiming.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      shell: bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}